
// FIX: Corrected import path for types
import type { Exercise } from '../types';

interface ExerciseGroup {
    group: string;
    exercises: Omit<Exercise, 'muscleGroup'>[];
}

export const ALL_EXERCISES_BY_GROUP: ExerciseGroup[] = [
    {
        group: "Chest",
        exercises: [
            { id: "chest_1", name: "Assisted Dip" },
            { id: "chest_2", name: "Band-Assisted Bench Press" },
            { id: "chest_3", name: "Bar Dip" },
            { id: "chest_4", name: "Bench Press" },
            { id: "chest_5", name: "Bench Press Against Band" },
            { id: "chest_6", name: "Board Press" },
            { id: "chest_7", name: "Cable Chest Press" },
            { id: "chest_8", name: "Clap Push-Up" },
            { id: "chest_9", name: "Close-Grip Bench Press" },
            { id: "chest_10", name: "Close-Grip Feet-Up Bench Press" },
            { id: "chest_11", name: "Cobra Push-Up" },
            { id: "chest_12", name: "Decline Bench Press" },
            { id: "chest_13", name: "Decline Push-Up" },
            { id: "chest_14", name: "Dumbbell Chest Fly" },
            { id: "chest_15", name: "Dumbbell Chest Press" },
            { id: "chest_16", name: "Dumbbell Decline Chest Press" },
            { id: "chest_17", name: "Dumbbell Floor Press" },
            { id: "chest_18", name: "Dumbbell Pullover" },
            { id: "chest_19", name: "Feet-Up Bench Press" },
            { id: "chest_20", name: "Floor Press" },
            { id: "chest_21", name: "Incline Bench Press" },
            { id: "chest_22", name: "Incline Dumbbell Press" },
            { id: "chest_23", name: "Incline Push-Up" },
            { id: "chest_24", name: "Kettlebell Floor Press" },
            { id: "chest_25", name: "Kneeling Incline Push-Up" },
            { id: "chest_26", name: "Kneeling Push-Up" },
            { id: "chest_27", name: "Machine Chest Fly" },
            { id: "chest_28", name: "Machine Chest Press" },
            { id: "chest_29", name: "Pec Deck" },
            { id: "chest_30", name: "Pin Bench Press" },
            { id: "chest_31", name: "Plank to Push-Up" },
            { id: "chest_32", name: "Push-Up" },
            { id: "chest_33", name: "Push-Up Against Wall" },
            { id: "chest_34", name: "Push-Ups With Feet in Rings" },
            { id: "chest_35", name: "Resistance Band Chest Fly" },
            { id: "chest_36", name: "Ring Dip" },
            { id: "chest_37", name: "Seated Cable Chest Fly" },
            { id: "chest_38", name: "Smith Machine Bench Press" },
            { id: "chest_39", name: "Smith Machine Incline Bench Press" },
            { id: "chest_40", name: "Smith Machine Reverse Grip Bench Press" },
            { id: "chest_41", name: "Standing Cable Chest Fly" },
            { id: "chest_42", name: "Standing Resistance Band Chest Fly" },
        ],
    },
    {
        group: "Shoulders",
        exercises: [
            { id: "shoulder_1", name: "Arnold Press" },
            { id: "shoulder_2", name: "Band External Shoulder Rotation" },
            { id: "shoulder_3", name: "Band Internal Shoulder Rotation" },
            { id: "shoulder_4", name: "Band Pull-Apart" },
            { id: "shoulder_5", name: "Banded Face Pull" },
            { id: "shoulder_6", name: "Barbell Front Raise" },
            { id: "shoulder_7", name: "Barbell Rear Delt Row" },
            { id: "shoulder_8", name: "Barbell Upright Row" },
            { id: "shoulder_9", name: "Behind the Neck Press" },
            { id: "shoulder_10", name: "Cable Internal Shoulder Rotation" },
            { id: "shoulder_11", name: "Cable External Shoulder Rotation" },
            { id: "shoulder_12", name: "Cable Front Raise" },
            { id: "shoulder_13", name: "Cable Lateral Raise" },
            { id: "shoulder_14", name: "Cable Rear Delt Row" },
            { id: "shoulder_15", name: "Cuban Press" },
            { id: "shoulder_16", name: "Devils Press" },
            { id: "shoulder_17", name: "Dumbbell Front Raise" },
            { id: "shoulder_18", name: "Dumbbell Horizontal Internal Shoulder Rotation" },
            { id: "shoulder_19", name: "Dumbbell Horizontal External Shoulder Rotation" },
            { id: "shoulder_20", name: "Dumbbell Lateral Raise" },
            { id: "shoulder_21", name: "Dumbbell Rear Delt Row" },
            { id: "shoulder_22", name: "Dumbbell Shoulder Press" },
            { id: "shoulder_23", name: "Face Pull" },
            { id: "shoulder_24", name: "Front Hold" },
            { id: "shoulder_25", name: "Handstand Push-Up" },
            { id: "shoulder_26", name: "Jerk" },
            { id: "shoulder_27", name: "Kettlebell Halo" },
            { id: "shoulder_28", name: "Kettlebell Press" },
            { id: "shoulder_29", name: "Kettlebell Push Press" },
            { id: "shoulder_30", name: "Landmine Press" },
            { id: "shoulder_31", name: "Lying Dumbbell External Shoulder Rotation" },
            { id: "shoulder_32", name: "Lying Dumbbell Internal Shoulder Rotation" },
            { id: "shoulder_33", name: "Machine Lateral Raise" },
            { id: "shoulder_34", name: "Machine Shoulder Press" },
            { id: "shoulder_35", name: "Monkey Row" },
            { id: "shoulder_36", name: "One-Arm Landmine Press" },
            { id: "shoulder_37", name: "Overhead Press" },
            { id: "shoulder_38", name: "Plate Front Raise" },
            { id: "shoulder_39", name: "Poliquin Raise" },
            { id: "shoulder_40", name: "Power Jerk" },
            { id: "shoulder_41", name: "Push Press" },
            { id: "shoulder_42", name: "Resistance Band Lateral Raise" },
            { id: "shoulder_43", name: "Reverse Cable Flyes" },
            { id: "shoulder_44", name: "Reverse Dumbbell Flyes" },
            { id: "shoulder_45", name: "Reverse Dumbbell Flyes on Incline Bench" },
            { id: "shoulder_46", name: "Reverse Machine Fly" },
            { id: "shoulder_47", name: "Seated Dumbbell Shoulder Press" },
            { id: "shoulder_48", name: "Seated Barbell Overhead Press" },
            { id: "shoulder_49", name: "Seated Kettlebell Press" },
            { id: "shoulder_50", name: "Seated Smith Machine Shoulder Press" },
            { id: "shoulder_51", name: "Smith Machine Landmine Press" },
            { id: "shoulder_52", name: "Snatch Grip Behind the Neck Press" },
            { id: "shoulder_53", name: "Squat Jerk" },
            { id: "shoulder_54", name: "Split Jerk" },
            { id: "shoulder_55", name: "Turkish Get-Up" },
            { id: "shoulder_56", name: "Wall Walk" },
            { id: "shoulder_57", name: "Z Press" },
        ],
    },
    {
        group: "Biceps",
        exercises: [
            { id: "bicep_1", name: "Barbell Curl" },
            { id: "bicep_2", name: "Barbell Preacher Curl" },
            { id: "bicep_3", name: "Bayesian Curl" },
            { id: "bicep_4", name: "Bodyweight Curl" },
            { id: "bicep_5", name: "Cable Crossover Bicep Curl" },
            { id: "bicep_6", name: "Cable Curl With Bar" },
            { id: "bicep_7", name: "Cable Curl With Rope" },
            { id: "bicep_8", name: "Concentration Curl" },
            { id: "bicep_9", name: "Drag Curl" },
            { id: "bicep_10", name: "Dumbbell Curl" },
            { id: "bicep_11", name: "Dumbbell Preacher Curl" },
            { id: "bicep_12", name: "Hammer Curl" },
            { id: "bicep_13", name: "Incline Dumbbell Curl" },
            { id: "bicep_14", name: "Kettlebell Curl" },
            { id: "bicep_15", name: "Lying Bicep Cable Curl on Bench" },
            { id: "bicep_16", name: "Lying Bicep Cable Curl on Floor" },
            { id: "bicep_17", name: "Machine Bicep Curl" },
            { id: "bicep_18", name: "Overhead Cable Curl" },
            { id: "bicep_19", name: "Reverse Barbell Curl" },
            { id: "bicep_20", name: "Reverse Dumbbell Curl" },
            { id: "bicep_21", name: "Resistance Band Curl" },
            { id: "bicep_22", name: "Spider Curl" },
            { id: "bicep_23", name: "Zottman Curl" },
        ],
    },
    {
        group: "Triceps",
        exercises: [
            { id: "tricep_1", name: "Barbell Standing Triceps Extension" },
            { id: "tricep_2", name: "Barbell Incline Triceps Extension" },
            { id: "tricep_3", name: "Barbell Lying Triceps Extension" },
            { id: "tricep_4", name: "Bench Dip" },
            { id: "tricep_5", name: "Crossbody Cable Triceps Extension" },
            { id: "tricep_6", name: "Close-Grip Push-Up" },
            { id: "tricep_7", name: "Dumbbell Lying Triceps Extension" },
            { id: "tricep_8", name: "Dumbbell Standing Triceps Extension" },
            { id: "tricep_9", name: "EZ Bar Lying Triceps Extension" },
            { id: "tricep_10", name: "Machine Overhead Triceps Extension" },
            { id: "tricep_11", name: "Overhead Cable Triceps Extension (Lower Position)" },
            { id: "tricep_12", name: "Overhead Cable Triceps Extension (Upper Position)" },
            { id: "tricep_13", name: "Smith Machine Skull Crushers" },
            { id: "tricep_14", name: "Tate Press" },
            { id: "tricep_15", name: "Tricep Bodyweight Extension" },
            { id: "tricep_16", name: "Tricep Pushdown With Bar" },
            { id: "tricep_17", name: "Tricep Pushdown With Rope" },
        ],
    },
    {
        group: "Legs",
        exercises: [
            { id: "leg_1", name: "Air Squat" },
            { id: "leg_2", name: "Banded Hip March" },
            { id: "leg_3", name: "Barbell Hack Squat" },
            { id: "leg_4", name: "Barbell Lunge" },
            { id: "leg_5", name: "Barbell Walking Lunge" },
            { id: "leg_6", name: "Belt Squat" },
            { id: "leg_7", name: "Body Weight Lunge" },
            { id: "leg_8", name: "Bodyweight Leg Curl" },
            { id: "leg_9", name: "Box Jump" },
            { id: "leg_10", name: "Box Squat" },
            { id: "leg_11", name: "Bulgarian Split Squat" },
            { id: "leg_12", name: "Cable Machine Hip Adduction" },
            { id: "leg_13", name: "Chair Squat" },
            { id: "leg_14", name: "Curtsy Lunge" },
            { id: "leg_15", name: "Dumbbell Lunge" },
            { id: "leg_16", name: "Dumbbell Walking Lunge" },
            { id: "leg_17", name: "Dumbbell Squat" },
            { id: "leg_18", name: "Front Squat" },
            { id: "leg_19", name: "Glute Ham Raise" },
            { id: "leg_20", name: "Goblet Squat" },
            { id: "leg_21", name: "Ground to Overhead" },
            { id: "leg_22", name: "Hack Squat Machine" },
            { id: "leg_23", name: "Half Air Squat" },
            { id: "leg_24", name: "Hip Adduction Against Band" },
            { id: "leg_25", name: "Hip Adduction Machine" },
            { id: "leg_26", name: "Jump Squat" },
            { id: "leg_27", name: "Jumping Lunge" },
            { id: "leg_28", name: "Kettlebell Front Squat" },
            { id: "leg_29", name: "Kettlebell Thrusters" },
            { id: "leg_30", name: "Landmine Hack Squat" },
            { id: "leg_31", name: "Landmine Squat" },
            { id: "leg_32", name: "Lateral Bound" },
            { id: "leg_33", name: "Leg Curl On Ball" },
            { id: "leg_34", name: "Leg Extension" },
            { id: "leg_35", name: "Leg Press" },
            { id: "leg_36", name: "Lying Leg Curl" },
            { id: "leg_37", name: "Nordic Hamstring Eccentric" },
            { id: "leg_38", name: "One-Legged Leg Extension" },
            { id: "leg_39", name: "One-Legged Lying Leg Curl" },
            { id: "leg_40", name: "One-Legged Seated Leg Curl" },
            { id: "leg_41", name: "Pause Squat" },
            { id: "leg_42", name: "Pin Squat" },
            { id: "leg_43", name: "Pistol Squat" },
            { id: "leg_44", name: "Poliquin Step-Up" },
            { id: "leg_45", name: "Prisoner Get Up" },
            { id: "leg_46", name: "Reverse Barbell Lunge" },
            { id: "leg_47", name: "Reverse Body Weight Lunge" },
            { id: "leg_48", name: "Reverse Dumbbell Lunge" },
            { id: "leg_49", name: "Reverse Nordic" },
            { id: "leg_50", name: "Romanian Deadlift" },
            { id: "leg_51", name: "Safety Bar Squat" },
            { id: "leg_52", name: "Seated Leg Curl" },
            { id: "leg_53", name: "Shallow Body Weight Lunge" },
            { id: "leg_54", name: "Side Lunges (Bodyweight)" },
            { id: "leg_55", name: "Smith Machine Bulgarian Split Squat" },
            { id: "leg_56", name: "Smith Machine Front Squat" },
            { id: "leg_57", name: "Smith Machine Lunge" },
            { id: "leg_58", name: "Smith Machine Romanian Deadlift" },
            { id: "leg_59", name: "Smith Machine Squat" },
            { id: "leg_60", name: "Sumo Squat" },
            { id: "leg_61", name: "Squat" },
            { id: "leg_62", name: "Standing Cable Leg Extension" },
            { id: "leg_63", name: "Standing Hip Flexor Raise" },
            { id: "leg_64", name: "Step Up" },
            { id: "leg_65", name: "Tibialis Raise" },
            { id: "leg_66", name: "Vertical Leg Press" },
            { id: "leg_67", name: "Zercher Squat" },
            { id: "leg_68", name: "Zombie Squat" },
        ],
    },
    {
        group: "Back",
        exercises: [
            { id: "back_1", name: "Assisted Chin-Up" },
            { id: "back_2", name: "Assisted Pull-Up" },
            { id: "back_3", name: "Back Extension" },
            { id: "back_4", name: "Banded Muscle-Up" },
            { id: "back_5", name: "Barbell Row" },
            { id: "back_6", name: "Barbell Shrug" },
            { id: "back_7", name: "Block Clean" },
            { id: "back_8", name: "Block Snatch" },
            { id: "back_9", name: "Cable Close Grip Seated Row" },
            { id: "back_10", name: "Cable Wide Grip Seated Row" },
            { id: "back_11", name: "Chest to Bar" },
            { id: "back_12", name: "Chin-Up" },
            { id: "back_13", name: "Clean" },
            { id: "back_14", name: "Clean and Jerk" },
            { id: "back_15", name: "Close-Grip Chin-Up" },
            { id: "back_16", name: "Close-Grip Lat Pulldown" },
            { id: "back_17", name: "Deadlift" },
            { id: "back_18", name: "Deficit Deadlift" },
            { id: "back_19", name: "Dumbbell Deadlift" },
            { id: "back_20", name: "Dumbbell Row" },
            { id: "back_21", name: "Dumbbell Shrug" },
            { id: "back_22", name: "Floor Back Extension" },
            { id: "back_23", name: "Good Morning" },
            { id: "back_24", name: "Gorilla Row" },
            { id: "back_25", name: "Hang Clean" },
            { id: "back_26", name: "Hang Power Clean" },
            { id: "back_27", name: "Hang Power Snatch" },
            { id: "back_28", name: "Hang Snatch" },
            { id: "back_29", name: "Inverted Row" },
            { id: "back_30", name: "Inverted Row with Underhand Grip" },
            { id: "back_31", name: "Jefferson Curl" },
            { id: "back_32", name: "Jumping Muscle-Up" },
            { id: "back_33", name: "Kettlebell Clean" },
            { id: "back_34", name: "Kettlebell Clean & Jerk" },
            { id: "back_35", name: "Kettlebell Clean & Press" },
            { id: "back_36", name: "Kettlebell Row" },
            { id: "back_37", name: "Kettlebell Snatch" },
            { id: "back_38", name: "Kettlebell Swing" },
            { id: "back_39", name: "Kroc Row" },
            { id: "back_40", name: "Lat Pulldown With Neutral Grip" },
            { id: "back_41", name: "Lat Pulldown With Pronated Grip" },
            { id: "back_42", name: "Lat Pulldown With Supinated Grip" },
            { id: "back_43", name: "Machine Lat Pulldown" },
            { id: "back_44", name: "Muscle-Up (Bar)" },
            { id: "back_45", name: "Muscle-Up (Rings)" },
            { id: "back_46", name: "Neutral Close-Grip Lat Pulldown" },
            { id: "back_47", name: "One-Handed Cable Row" },
            { id: "back_48", name: "One-Handed Kettlebell Swing" },
            { id: "back_49", name: "One-Handed Lat Pulldown" },
            { id: "back_50", name: "Pause Deadlift" },
            { id: "back_51", name: "Pendlay Row" },
            { id: "back_52", name: "Power Clean" },
            { id: "back_53", name: "Power Snatch" },
            { id: "back_54", name: "Pull-Up" },
            { id: "back_55", name: "Pull-Up With a Neutral Grip" },
            { id: "back_56", name: "Rack Pull" },
            { id: "back_57", name: "Renegade Row" },
            { id: "back_58", name: "Ring Pull-Up" },
            { id: "back_59", name: "Ring Row" },
            { id: "back_60", name: "Scap Pull-Up" },
            { id: "back_61", name: "Seal Row" },
            { id: "back_62", name: "Seated Machine Row" },
            { id: "back_63", name: "Single Leg Deadlift with Kettlebell" },
            { id: "back_64", name: "Smith Machine Deadlift" },
            { id: "back_65", name: "Smith Machine One-Handed Row" },
            { id: "back_66", name: "Snatch" },
            { id: "back_67", name: "Snatch Grip Deadlift" },
            { id: "back_68", name: "Stiff-Legged Deadlift" },
            { id: "back_69", name: "Straight Arm Lat Pulldown" },
            { id: "back_70", name: "Sumo Deadlift" },
            { id: "back_71", name: "Superman Raise" },
            { id: "back_72", name: "T-Bar Row" },
            { id: "back_73", name: "Towel Row" },
            { id: "back_74", name: "Trap Bar Deadlift With High Handles" },
            { id: "back_75", name: "Trap Bar Deadlift With Low Handles" },
        ],
    },
    {
        group: "Glutes",
        exercises: [
            { id: "glute_1", name: "Banded Side Kicks" },
            { id: "glute_2", name: "Cable Glute Kickback" },
            { id: "glute_3", name: "Cable Pull Through" },
            { id: "glute_4", name: "Cable Machine Hip Abduction" },
            { id: "glute_5", name: "Clamshells" },
            { id: "glute_6", name: "Cossack Squat" },
            { id: "glute_7", name: "Death March with Dumbbells" },
            { id: "glute_8", name: "Donkey Kicks" },
            { id: "glute_9", name: "Dumbbell Romanian Deadlift" },
            { id: "glute_10", name: "Dumbbell Frog Pumps" },
            { id: "glute_11", name: "Fire Hydrants" },
            { id: "glute_12", name: "Frog Pumps" },
            { id: "glute_13", name: "Glute Bridge" },
            { id: "glute_14", name: "Hip Abduction Against Band" },
            { id: "glute_15", name: "Hip Abduction Machine" },
            { id: "glute_16", name: "Hip Thrust" },
            { id: "glute_17", name: "Hip Thrust Machine" },
            { id: "glute_18", name: "Hip Thrust With Band Around Knees" },
            { id: "glute_19", name: "Kettlebell Windmill" },
            { id: "glute_20", name: "Lateral Walk With Band" },
            { id: "glute_21", name: "Machine Glute Kickbacks" },
            { id: "glute_22", name: "One-Legged Glute Bridge" },
            { id: "glute_23", name: "One-Legged Hip Thrust" },
            { id: "glute_24", name: "Reverse Hyperextension" },
            { id: "glute_25", name: "Romanian Deadlift" },
            { id: "glute_26", name: "Smith Machine Hip Thrust" },
            { id: "glute_27", name: "Single Leg Romanian Deadlift" },
            { id: "glute_28", name: "Standing Hip Abduction Against Band" },
            { id: "glute_29", name: "Standing Glute Kickback in Machine" },
            { id: "glute_30", name: "Standing Glute Push Down" },
            { id: "glute_31", name: "Step Up" },
        ],
    },
    {
        group: "Abs",
        exercises: [
            { id: "ab_1", name: "Ball Slams" },
            { id: "ab_2", name: "Bicycle Crunch" },
            { id: "ab_3", name: "Cable Crunch" },
            { id: "ab_4", name: "Copenhagen Plank" },
            { id: "ab_5", name: "Core Twist" },
            { id: "ab_6", name: "Crunch" },
            { id: "ab_7", name: "Dead Bug" },
            { id: "ab_8", name: "Dead Bug With Dumbbells" },
            { id: "ab_9", name: "Dragon Flag" },
            { id: "ab_10", name: "Dumbbell Side Bend" },
            { id: "ab_11", name: "Hanging Knee Raise" },
            { id: "ab_12", name: "Hanging Leg Raise" },
            { id: "ab_13", name: "Hanging Sit-Up" },
            { id: "ab_14", name: "Hanging Windshield Wiper" },
            { id: "ab_15", name: "High to Low Wood Chop with Band" },
            { id: "ab_16", name: "High to Low Wood Chop with Cable" },
            { id: "ab_17", name: "Hollow Body Crunch" },
            { id: "ab_18", name: "Hollow Hold" },
            { id: "ab_19", name: "Horizontal Wood Chop with Band" },
            { id: "ab_20", name: "Horizontal Wood Chop with Cable" },
            { id: "ab_21", name: "Jackknife Sit-Up" },
            { id: "ab_22", name: "Kettlebell Plank Pull Through" },
            { id: "ab_23", name: "Kneeling Ab Wheel Roll-Out" },
            { id: "ab_24", name: "Kneeling Plank" },
            { id: "ab_25", name: "Kneeling Side Plank" },
            { id: "ab_26", name: "Landmine Rotation" },
            { id: "ab_27", name: "L-Sit" },
            { id: "ab_28", name: "Low to High Wood Chop with Band" },
            { id: "ab_29", name: "Low to High Wood Chop with Cable" },
            { id: "ab_30", name: "Lying Leg Raise" },
            { id: "ab_31", name: "Lying Windshield Wiper" },
            { id: "ab_32", name: "Lying Windshield Wiper with Bent Knees" },
            { id: "ab_33", name: "Machine Crunch" },
            { id: "ab_34", name: "Mountain Climbers" },
            { id: "ab_35", name: "Oblique Crunch" },
            { id: "ab_36", name: "Oblique Sit-Up" },
            { id: "ab_37", name: "Plank" },
            { id: "ab_38", name: "Plank with Leg Lifts" },
            { id: "ab_39", name: "Plank with Shoulder Taps" },
            { id: "ab_40", name: "Side Plank" },
            { id: "ab_41", name: "Sit-Up" },
            { id: "ab_42", name: "Weighted Plank" },
        ],
    },
    {
        group: "Calves",
        exercises: [
            { id: "calve_1", name: "Barbell Standing Calf Raise" },
            { id: "calve_2", name: "Barbell Seated Calf Raise" },
            { id: "calve_3", name: "Calf Raise in Leg Press" },
            { id: "calve_4", name: "Donkey Calf Raise" },
            { id: "calve_5", name: "Eccentric Heel Drop" },
            { id: "calve_6", name: "Heel Raise" },
            { id: "calve_7", name: "Seated Calf Raise" },
            { id: "calve_8", name: "Standing Calf Raise" },
        ],
    },
    {
        group: "Forearms & Grip",
        exercises: [
            { id: "forearm_1", name: "Barbell Wrist Curl" },
            { id: "forearm_2", name: "Barbell Wrist Curl Behind the Back" },
            { id: "forearm_3", name: "Bar Hang" },
            { id: "forearm_4", name: "Dumbbell Wrist Curl" },
            { id: "forearm_5", name: "Farmers Walk" },
            { id: "forearm_6", name: "Fat Bar Deadlift" },
            { id: "forearm_7", name: "Gripper" },
            { id: "forearm_8", name: "One-Handed Bar Hang" },
            { id: "forearm_9", name: "Plate Pinch" },
            { id: "forearm_10", name: "Plate Wrist Curl" },
            { id: "forearm_11", name: "Towel Pull-Up" },
            { id: "forearm_12", name: "Wrist Roller" },
            { id: "forearm_13", name: "Barbell Wrist Extension" },
            { id: "forearm_14", name: "Dumbbell Wrist Extension" },
        ],
    },
    {
        group: "Neck",
        exercises: [
            { id: "neck_1", name: "Lying Neck Curl" },
            { id: "neck_2", name: "Lying Neck Extension" },
        ],
    },
    {
        group: "Cardio",
        exercises: [
            { id: "cardio_1", name: "Rowing Machine" },
            { id: "cardio_2", name: "Stationary Bike" },
        ],
    },
];